services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SOLANA_NETWORK=https://api.devnet.solana.com
      - NEXT_PUBLIC_PROGRAM_ID=KronosDApp1111111111111111111111111111111111
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - kronos-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - kronos-network

networks:
  kronos-network:
    driver: bridge
